from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def _resolve_input_path(path_str: str) -> Path:
    path = Path(path_str)
    if path.is_absolute():
        return path.resolve()
    return (ROOT / path).resolve()


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d-%H-%M-%S")


def _build_main_table(score: dict[str, Any]) -> list[str]:
    overall = dict(score.get("overall") or {})
    per_domain = dict(score.get("per_domain") or {})
    rows = [
        "| Domain | Checkpoints | U | A | F | MGS | Action Acc. |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for domain in ["medical", "office", "education", "household"]:
        row = dict(per_domain.get(domain) or {})
        rows.append(
            f"| {domain.title()} | {int(row.get('checkpoints') or 0)} | {float(row.get('U') or 0.0):.4f} | {float(row.get('A') or 0.0):.4f} | {float(row.get('F') or 0.0):.4f} | {float(row.get('MGS') or 0.0):.4f} | {float(row.get('action_accuracy') or 0.0):.4f} |"
        )
    rows.append(
        f"| Overall | {sum(int(dict(per_domain.get(d) or {}).get('checkpoints') or 0) for d in per_domain)} | {float(overall.get('U') or 0.0):.4f} | {float(overall.get('A') or 0.0):.4f} | {float(overall.get('F') or 0.0):.4f} | {float(overall.get('MGS') or 0.0):.4f} | {float(overall.get('action_accuracy') or 0.0):.4f} |"
    )
    return rows


def _build_ablation_table(rows: list[dict[str, str]]) -> list[str]:
    lines = [
        "| Variant | U | A | F | MGS | Delta MGS |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['label']} | {float(row['U']):.4f} | {float(row['A']):.4f} | {float(row['F']):.4f} | {float(row['MGS']):.4f} | {float(row['delta_mgs']):+.4f} |"
        )
    return lines


def _build_case_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = [
        "| Category | Domain | Checkpoint | Action |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(f"| {row['category']} | {row['domain']} | {row['checkpoint_id']} | {row['pred_action']} |")
    return lines


def _write_tex(path: Path, score: dict[str, Any], ablations: list[dict[str, str]], cases: list[dict[str, Any]]) -> None:
    per_domain = dict(score.get("per_domain") or {})
    overall = dict(score.get("overall") or {})
    lines = [
        "% Auto-generated by scripts/build_paper_report.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "Domain & Checkpoints & U & A & F & MGS & Action Acc. \\\\",
        "\\midrule",
    ]
    for domain in ["medical", "office", "education", "household"]:
        row = dict(per_domain.get(domain) or {})
        lines.append(
            f"{domain.title()} & {int(row.get('checkpoints') or 0)} & {float(row.get('U') or 0.0):.4f} & {float(row.get('A') or 0.0):.4f} & {float(row.get('F') or 0.0):.4f} & {float(row.get('MGS') or 0.0):.4f} & {float(row.get('action_accuracy') or 0.0):.4f} \\\\"
        )
    lines.extend(
        [
            "\\midrule",
            f"Overall & {sum(int(dict(per_domain.get(d) or {}).get('checkpoints') or 0) for d in per_domain)} & {float(overall.get('U') or 0.0):.4f} & {float(overall.get('A') or 0.0):.4f} & {float(overall.get('F') or 0.0):.4f} & {float(overall.get('MGS') or 0.0):.4f} & {float(overall.get('action_accuracy') or 0.0):.4f} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Gov-Mem GateMem results under the official-compatible reporting pipeline.}",
            "\\end{table}",
            "",
            "\\begin{table}[t]",
            "\\centering",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Variant & U & A & F & MGS & $\\Delta$MGS \\\\",
            "\\midrule",
        ]
    )
    for row in ablations:
        lines.append(
            f"{row['label'].replace('_', ' ')} & {float(row['U']):.4f} & {float(row['A']):.4f} & {float(row['F']):.4f} & {float(row['MGS']):.4f} & {float(row['delta_mgs']):+.4f} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Gov-Mem ablation summary.}",
            "\\end{table}",
            "",
            "\\begin{table}[t]",
            "\\centering",
            "\\begin{tabular}{llll}",
            "\\toprule",
            "Category & Domain & Checkpoint & Action \\\\",
            "\\midrule",
        ]
    )
    for row in cases:
        lines.append(
            f"{row['category'].replace('_', ' ')} & {row['domain']} & {row['checkpoint_id'].replace('_', '\\_')} & {row['pred_action']} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Representative Gov-Mem case studies.}",
            "\\end{table}",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_result_md(path: Path, score: dict[str, Any], ablations: list[dict[str, str]], cases: list[dict[str, Any]], sources: dict[str, str]) -> None:
    lines = [
        "# GateMem Gov-Mem Results",
        "",
        f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Evaluation Setting",
        "",
        f"- Official score file: `{sources['official_score']}`",
        f"- Ablation CSV: `{sources['ablation_csv']}`",
        f"- Case-study JSONL: `{sources['case_study_jsonl']}`",
        "- Runtime API: `yunwu`",
        "- Official scorer: `third_party/GateMem-official/bench/scripts/score_predictions.py`",
        "- LLM judge: `False`",
        "",
        "## Main Table",
        "",
    ]
    lines.extend(_build_main_table(score))
    lines.extend(["", "## Ablation Table", ""])
    lines.extend(_build_ablation_table(ablations))
    lines.extend(["", "## Case Studies", ""])
    lines.extend(_build_case_table(cases))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the Gov-Mem paper-facing report and TeX tables.")
    parser.add_argument("--official_score", default="outputs/gov_mem_v0_strong/official_score.json")
    parser.add_argument("--ablation_csv", required=True)
    parser.add_argument("--case_study_jsonl", required=True)
    parser.add_argument("--output_md", default="outputs/reports/gov_mem_paper_report.md")
    parser.add_argument("--output_tex", default="outputs/reports/gov_mem_paper_tables.tex")
    parser.add_argument("--result_dir", default="experiments/result")
    parser.add_argument("--result_name", default="GateMem_Gov-Mem_paper_report.md")
    args = parser.parse_args()

    official_score_path = _resolve_input_path(args.official_score)
    ablation_csv_path = _resolve_input_path(args.ablation_csv)
    case_study_jsonl_path = _resolve_input_path(args.case_study_jsonl)
    official_score = _load_json(official_score_path)
    ablations = _load_csv(ablation_csv_path)
    cases = _load_jsonl(case_study_jsonl_path)

    output_md = (ROOT / args.output_md).resolve()
    output_tex = (ROOT / args.output_tex).resolve()
    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_tex.parent.mkdir(parents=True, exist_ok=True)

    sources = {
        "official_score": str(official_score_path),
        "ablation_csv": str(ablation_csv_path),
        "case_study_jsonl": str(case_study_jsonl_path),
    }
    _write_result_md(output_md, official_score, ablations, cases, sources)
    _write_tex(output_tex, official_score, ablations, cases)

    result_dir = (ROOT / args.result_dir).resolve()
    result_dir.mkdir(parents=True, exist_ok=True)
    result_md = result_dir / f"{_timestamp()}_{args.result_name}"
    _write_result_md(result_md, official_score, ablations, cases, sources)
    print(f"report_md={output_md}")
    print(f"report_tex={output_tex}")
    print(f"result_md={result_md}")


if __name__ == "__main__":
    main()
